### ISSUE TITLE
waiting for locator("#USER_DROPDOWN_ID > span.DFKWwVItcycZV1bKUOyay > i") to be visible

### ISSUE THREAD

**Issue by BrodyVossen** [nssharmaofficial/reddit-hole#1]
The script intermittently fails when waiting for the dropdown menu selector to become visible, resulting in a TimeoutError. This error occurs inconsistently; sometimes the selector is found immediately, while other times it causes a timeout. The selector in question is:

javascript
Copy code
"#USER_DROPDOWN_ID > span.DFKWwVItcycZV1bKUOyay > i"
Steps to Reproduce:

Run the script.
Observe the varying behavior when the script waits for the dropdown menu selector.
Expected Behavior:
The script should consistently locate the dropdown menu selector without timing out.

Actual Behavior:
Inconsistent detection of the dropdown menu selector, leading to timeout errors.

Comments mode is on for subreddit: askreddit
Logged in to Reddit successfully!
Chosen thread: What are some signs, that you're conventionally ugly? -- Score: 7970
Saved:  ./assets/temp/1ei7sgm/mp3/title.mp3
Saved:  ./assets/temp/1ei7sgm/png/fancytitle.png
10 comments are chosen
Launching browser...
Waiting for dropdown menu selector...
Timeout waiting for dropdown menu selector: Page.wait_for_selector: Timeout 10000ms exceeded.
Call log:
waiting for locator("#USER_DROPDOWN_ID > span.DFKWwVItcycZV1bKUOyay > i") to be visible

Traceback (most recent call last):
  File "c:\Users\engineering3\Desktop\reddit-hole-main\main.py", line 205, in <module>
    main()
  File "c:\Users\engineering3\Desktop\reddit-hole-main\main.py", line 137, in main
    reddit.get_screenshots_of_reddit_posts(reddit_thread=thread,
  File "c:\Users\engineering3\Desktop\reddit-hole-main\utils\reddit.py", line 127, in get_screenshots_of_reddit_posts
    raise e
  File "c:\Users\engineering3\Desktop\reddit-hole-main\utils\reddit.py", line 120, in get_screenshots_of_reddit_posts
    page.wait_for_selector(dropdown_menu_selector, timeout=10000)  # Increase timeout
  File "C:\Users\engineering3\Desktop\reddit-hole-main\env\lib\site-packages\playwright\sync_api\_generated.py", line 7834, in wait_for_selector
    self._sync(
  File "C:\Users\engineering3\Desktop\reddit-hole-main\env\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync     
    return task.result()
  File "C:\Users\engineering3\Desktop\reddit-hole-main\env\lib\site-packages\playwright\_impl\_page.py", line 392, in wait_for_selector
    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
  File "C:\Users\engineering3\Desktop\reddit-hole-main\env\lib\site-packages\playwright\_impl\_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Users\engineering3\Desktop\reddit-hole-main\env\lib\site-packages\playwright\_impl\_connection.py", line 59, in send      
    return await self._connection.wrap_api_call(
  File "C:\Users\engineering3\Desktop\reddit-hole-main\env\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Page.wait_for_selector: Timeout 10000ms exceeded.
Call log:

**Comment by nssharmaofficial** [comment]
@BrodyVossen I have the same issue as you - it gets fixed when I connect to my phone's data instead of WiFi. I believe it is only because of poor (slow) connections. That would pretty much explain the inconsistency too.

**Comment by Beertie** [comment]
Same issue here, watching for updates.

**Comment by nssharmaofficial** [comment]
@Beertie @BrodyVossen Increased timeout when browsing. Try it also with different/better connection. Let me know if that helped.

**Comment by BrodyVossen** [comment]
Here is a updated reddit.py version that worked for me

import praw
from praw.reddit import Reddit
from praw.models import Submission, MoreComments
from utils.helpers import load_config, load_database, sanitize_text
from tinydb import Query
import json
from playwright.sync_api import sync_playwright, ViewportSize, BrowserContext, TimeoutError as PlaywrightTimeoutError, Error as PlaywrightError
import os


def login() -> Reddit:
    """
    Logs into Reddit using credentials from the configuration file.

    Returns:
        Reddit: The Reddit instance after successful login.

    Raises:
        Exception: If login fails, the exception is returned.
    """
    my_config = load_config()
    try:
        reddit = praw.Reddit(
            client_id=my_config['RedditCredential']['client_id'],
            client_secret=my_config['RedditCredential']['client_secret'],
            user_agent=my_config['RedditCredential']['user_agent'],
            username=my_config["RedditCredential"]["username"],
            password=my_config["RedditCredential"]["passkey"],
            check_for_async=False
        )
        print("Logged in to Reddit successfully!")
        return reddit
    except Exception as e:
        print(f"Failed to login to Reddit: {e}")
        raise e


def get_thread(reddit: Reddit, subreddit: str) -> Submission:
    """
    Retrieves the top thread from a subreddit that is not already in the database.

    Args:
        reddit (Reddit): The Reddit instance.
        subreddit (str): The name of the subreddit.

    Returns:
        Submission: The top thread not already in the database.
    """
    # Access the subreddit
    subreddit_instance = reddit.subreddit(subreddit)

    # Get the top threads of the week
    threads = subreddit_instance.top('week')

    # Sort threads based on the number of upvotes in descending order
    sorted_threads = sorted(threads, key=lambda x: x.score, reverse=True)

    # Load the database
    db = load_database()
    chosen_thread = None

    # Find the top thread that is not already in the database
    for thread in sorted_threads:
        if not db.search(Query().id == str(thread.id)):
            print(f"Chosen thread: {thread.title} -- Score: {thread.score}")
            chosen_thread = thread
            break

    db.close()
    return chosen_thread


def get_comments(thread: Submission) -> list:
    """
    Retrieves and sanitizes top-level comments from a Reddit thread.

    Args:
        thread (Submission): The Reddit thread.

    Returns:
        list: A list of sanitized top-level comments.
    """
    # Load configuration settings
    my_config = load_config()
    topn = my_config['Reddit']['topn_comments']
    comments = []

    # Iterate through the top-level comments of the thread
    for top_level_comment in thread.comments:
        if len(comments) >= topn:
            break
        if isinstance(top_level_comment, MoreComments):
            continue
        if top_level_comment.body in ["[removed]", "[deleted]"]:
            continue
        if not top_level_comment.stickied:
            sanitized = sanitize_text(top_level_comment.body)
            if sanitized and (my_config["Reddit"]["min_comment_length"] <= len(top_level_comment.body)
                              and len(top_level_comment.body) <= my_config["Reddit"]["max_comment_length"]):
                comments.append(top_level_comment)

    print(f"{len(comments)} comments are chosen")
    return comments


def clear_cookie_by_name(context: BrowserContext, cookie_name: str):
    """
    Clears a specific cookie by its name in the browser context.

    Args:
        context (BrowserContext): The browser context.
        cookie_name (str): The name of the cookie to clear.
    """
    # Get all cookies in the browser context
    cookies = context.cookies()

    # Filter out the cookie that needs to be cleared
    filtered_cookies = [cookie for cookie in cookies if cookie["name"] != cookie_name]

    # Clear all cookies
    context.clear_cookies()

    # Add back the filtered cookies (excluding the one to be cleared)
    context.add_cookies(filtered_cookies)


def get_screenshots_of_reddit_posts(reddit_thread: Submission, reddit_comments: list):
    """
    Takes screenshots of a Reddit thread and its comments using Playwright.

    Args:
        reddit_thread (Submission): The Reddit thread.
        reddit_comments (list): A list of Reddit comments.
    """
    my_config = load_config()

    # Settings for screenshot dimensions
    W = my_config["settings"]["resolution_h"]
    H = my_config["settings"]["resolution_w"]

    try:
        with sync_playwright() as p:
            print("Launching browser...")

            browser = p.chromium.launch(headless=True)

            theme = my_config["settings"]["theme"]

            # Calculate device scale factor
            dsf = (W // 600) + 1

            # Create a new browser context with specified settings
            context = browser.new_context(
                locale="en-us",
                color_scheme=theme,
                viewport=ViewportSize(width=W, height=H),
                device_scale_factor=dsf,
                user_agent=my_config["RedditCredential"]["user_agent"]
            )

            with open(f"./assets/cookie-{theme}-mode.json", encoding="utf-8") as cookie_file:
                cookies = json.load(cookie_file)
                cookie_file.close()
                context.add_cookies(cookies)

            # Open a new page and log in to Reddit
            page = context.new_page()
            page.goto("https://www.reddit.com/login", timeout=0)
            page.set_viewport_size(ViewportSize(width=1920, height=1080))
            page.wait_for_load_state()

            # Fill in login credentials and submit
            page.locator('input[name="username"]').fill(my_config["RedditCredential"]["username"])
            page.locator('input[name="password"]').fill(my_config["RedditCredential"]["passkey"])
            page.get_by_role("button", name="Log In").click()
            page.wait_for_timeout(5000)

            # Handle Reddit redesign opt-out if necessary
            if page.locator("#redesign-beta-optin-btn").is_visible():
                clear_cookie_by_name(context, "redesign_optout")
                page.reload()

            # Navigate to the Reddit thread
            page.goto(f"https://new.reddit.com{reddit_thread.permalink}", timeout=0)
            page.set_viewport_size(ViewportSize(width=W, height=H))
            page.wait_for_timeout(10000)

            try:
                # Wait for the dropdown menu to be visible and click it
                dropdown_menu_selector = "#USER_DROPDOWN_ID > span.DFKWwVItcycZV1bKUOyay > i"
                page.wait_for_load_state('load')
                page.wait_for_selector(dropdown_menu_selector, timeout=60000)
                page.locator(dropdown_menu_selector).click()
            except PlaywrightTimeoutError:
                print("TimeoutError: The dropdown menu did not appear within 60 seconds.")
            except PlaywrightError as pe:
                if 'Event loop is closed' in str(pe):
                    print("PlaywrightError: Event loop is closed! Is Playwright already stopped?")
                else:
                    print(f"PlaywrightError: {pe}")
            except Exception as e:
                print(f"An unexpected error occurred: {e}")
                # Optionally, log the full stack trace
                import traceback
                traceback.print_exc()

            # Locate and click the dark mode button
            dark_mode_button_selector = "button[aria-checked='false'][role='switch']"
            dark_mode_button = page.locator(dark_mode_button_selector)

            # Ensure the dark mode button is visible
            if dark_mode_button.is_visible():
                is_dark_mode_enabled = dark_mode_button.get_attribute("aria-checked") == "true"
                if theme == "dark" and not is_dark_mode_enabled:
                    dark_mode_button.click()
                elif theme == "light" and is_dark_mode_enabled:
                    dark_mode_button.click()
            page.wait_for_timeout(2000)

            # Proceed with nsfw
            nsfw_proceed_button = (
                "#t3_12hmbug > div > div._3xX726aBn29LDbsDtzr_6E._1Ap4F5maDtT1E1YuCiaO0r"
                ".D3IL3FD0RFy_mkKLPwL4 > div > div > button"
            )
            if page.locator(nsfw_proceed_button).is_visible():
                page.locator(nsfw_proceed_button).click()
                page.wait_for_load_state()

            # Take screenshot of the post content
            op_path = f"./assets/temp/{reddit_thread.id}/png/title.png"
            if my_config["settings"]["zoom"] != 1:
                zoom = my_config["settings"]["zoom"]
                page.evaluate(f"document.body.style.zoom={zoom}")
                location = page.locator('[data-test-id="post-content"]').bounding_box()
                for key in location:
                    location[key] = float("{:.2f}".format(location[key] * zoom))
                page.screenshot(clip=location, path=op_path)
                location = page.locator('[data-adclicklocation="title"]').bounding_box()
                for key in location:
                    location[key] = float("{:.2f}".format(location[key] * zoom))
            else:
                page.locator('[data-test-id="post-content"]').screenshot(path=op_path)
            print("Saved: ", op_path)
            # print("Screenshot for OP completed")

            # Take screenshots of the comments
            for idx, comment in enumerate(reddit_comments):
                comments_path = f"./assets/temp/{reddit_thread.id}/png/{idx}.png"

                if page.locator('[data-testid="content-gate"]').is_visible():
                    page.locator('[data-testid="content-gate"] button').click()

                page.goto(f'https://new.reddit.com{comment.permalink}', timeout=0)
                if my_config["settings"]["zoom"] != 1:
                    zoom = my_config["settings"]["zoom"]
                    page.evaluate(f"document.body.style.zoom={zoom}")
                    location = page.locator(f"#t1_{comment.id}").bounding_box()
                    for key in location:
                        location[key] = float("{:.2f}".format(location[key] * zoom))
                    page.screenshot(clip=location, path=comments_path)
                else:
                    page.locator(f"#t1_{comment.id}").screenshot(path=comments_path)
                print("Saved: ", comments_path)
                # print(f"Screenshot for {idx + 1} comment out of {len(reddit_comments)}")

            browser.close()

        print("Screenshots downloaded successfully.")
    except Exception as e:
        print(f"An error occurred while taking screenshots: {e}")
        import traceback
        traceback.print_exc()

**Comment by BrodyVossen** [comment]
> Here is a updated reddit.py version that worked for me
> 
> import praw from praw.reddit import Reddit from praw.models import Submission, MoreComments from utils.helpers import load_config, load_database, sanitize_text from tinydb import Query import json from playwright.sync_api import sync_playwright, ViewportSize, BrowserContext, TimeoutError as PlaywrightTimeoutError, Error as PlaywrightError import os
> 
> def login() -> Reddit: """ Logs into Reddit using credentials from the configuration file.
> 
> ```
> Returns:
>     Reddit: The Reddit instance after successful login.
> 
> Raises:
>     Exception: If login fails, the exception is returned.
> """
> my_config = load_config()
> try:
>     reddit = praw.Reddit(
>         client_id=my_config['RedditCredential']['client_id'],
>         client_secret=my_config['RedditCredential']['client_secret'],
>         user_agent=my_config['RedditCredential']['user_agent'],
>         username=my_config["RedditCredential"]["username"],
>         password=my_config["RedditCredential"]["passkey"],
>         check_for_async=False
>     )
>     print("Logged in to Reddit successfully!")
>     return reddit
> except Exception as e:
>     print(f"Failed to login to Reddit: {e}")
>     raise e
> ```
> 
> def get_thread(reddit: Reddit, subreddit: str) -> Submission: """ Retrieves the top thread from a subreddit that is not already in the database.
> 
> ```
> Args:
>     reddit (Reddit): The Reddit instance.
>     subreddit (str): The name of the subreddit.
> 
> Returns:
>     Submission: The top thread not already in the database.
> """
> # Access the subreddit
> subreddit_instance = reddit.subreddit(subreddit)
> 
> # Get the top threads of the week
> threads = subreddit_instance.top('week')
> 
> # Sort threads based on the number of upvotes in descending order
> sorted_threads = sorted(threads, key=lambda x: x.score, reverse=True)
> 
> # Load the database
> db = load_database()
> chosen_thread = None
> 
> # Find the top thread that is not already in the database
> for thread in sorted_threads:
>     if not db.search(Query().id == str(thread.id)):
>         print(f"Chosen thread: {thread.title} -- Score: {thread.score}")
>         chosen_thread = thread
>         break
> 
> db.close()
> return chosen_thread
> ```
> 
> def get_comments(thread: Submission) -> list: """ Retrieves and sanitizes top-level comments from a Reddit thread.
> 
> ```
> Args:
>     thread (Submission): The Reddit thread.
> 
> Returns:
>     list: A list of sanitized top-level comments.
> """
> # Load configuration settings
> my_config = load_config()
> topn = my_config['Reddit']['topn_comments']
> comments = []
> 
> # Iterate through the top-level comments of the thread
> for top_level_comment in thread.comments:
>     if len(comments) >= topn:
>         break
>     if isinstance(top_level_comment, MoreComments):
>         continue
>     if top_level_comment.body in ["[removed]", "[deleted]"]:
>         continue
>     if not top_level_comment.stickied:
>         sanitized = sanitize_text(top_level_comment.body)
>         if sanitized and (my_config["Reddit"]["min_comment_length"] <= len(top_level_comment.body)
>                           and len(top_level_comment.body) <= my_config["Reddit"]["max_comment_length"]):
>             comments.append(top_level_comment)
> 
> print(f"{len(comments)} comments are chosen")
> return comments
> ```
> 
> def clear_cookie_by_name(context: BrowserContext, cookie_name: str): """ Clears a specific cookie by its name in the browser context.
> 
> ```
> Args:
>     context (BrowserContext): The browser context.
>     cookie_name (str): The name of the cookie to clear.
> """
> # Get all cookies in the browser context
> cookies = context.cookies()
> 
> # Filter out the cookie that needs to be cleared
> filtered_cookies = [cookie for cookie in cookies if cookie["name"] != cookie_name]
> 
> # Clear all cookies
> context.clear_cookies()
> 
> # Add back the filtered cookies (excluding the one to be cleared)
> context.add_cookies(filtered_cookies)
> ```
> 
> def get_screenshots_of_reddit_posts(reddit_thread: Submission, reddit_comments: list): """ Takes screenshots of a Reddit thread and its comments using Playwright.
> 
> ```
> Args:
>     reddit_thread (Submission): The Reddit thread.
>     reddit_comments (list): A list of Reddit comments.
> """
> my_config = load_config()
> 
> # Settings for screenshot dimensions
> W = my_config["settings"]["resolution_h"]
> H = my_config["settings"]["resolution_w"]
> 
> try:
>     with sync_playwright() as p:
>         print("Launching browser...")
> 
>         browser = p.chromium.launch(headless=True)
> 
>         theme = my_config["settings"]["theme"]
> 
>         # Calculate device scale factor
>         dsf = (W // 600) + 1
> 
>         # Create a new browser context with specified settings
>         context = browser.new_context(
>             locale="en-us",
>             color_scheme=theme,
>             viewport=ViewportSize(width=W, height=H),
>             device_scale_factor=dsf,
>             user_agent=my_config["RedditCredential"]["user_agent"]
>         )
> 
>         with open(f"./assets/cookie-{theme}-mode.json", encoding="utf-8") as cookie_file:
>             cookies = json.load(cookie_file)
>             cookie_file.close()
>             context.add_cookies(cookies)
> 
>         # Open a new page and log in to Reddit
>         page = context.new_page()
>         page.goto("https://www.reddit.com/login", timeout=0)
>         page.set_viewport_size(ViewportSize(width=1920, height=1080))
>         page.wait_for_load_state()
> 
>         # Fill in login credentials and submit
>         page.locator('input[name="username"]').fill(my_config["RedditCredential"]["username"])
>         page.locator('input[name="password"]').fill(my_config["RedditCredential"]["passkey"])
>         page.get_by_role("button", name="Log In").click()
>         page.wait_for_timeout(5000)
> 
>         # Handle Reddit redesign opt-out if necessary
>         if page.locator("#redesign-beta-optin-btn").is_visible():
>             clear_cookie_by_name(context, "redesign_optout")
>             page.reload()
> 
>         # Navigate to the Reddit thread
>         page.goto(f"https://new.reddit.com{reddit_thread.permalink}", timeout=0)
>         page.set_viewport_size(ViewportSize(width=W, height=H))
>         page.wait_for_timeout(10000)
> 
>         try:
>             # Wait for the dropdown menu to be visible and click it
>             dropdown_menu_selector = "#USER_DROPDOWN_ID > span.DFKWwVItcycZV1bKUOyay > i"
>             page.wait_for_load_state('load')
>             page.wait_for_selector(dropdown_menu_selector, timeout=60000)
>             page.locator(dropdown_menu_selector).click()
>         except PlaywrightTimeoutError:
>             print("TimeoutError: The dropdown menu did not appear within 60 seconds.")
>         except PlaywrightError as pe:
>             if 'Event loop is closed' in str(pe):
>                 print("PlaywrightError: Event loop is closed! Is Playwright already stopped?")
>             else:
>                 print(f"PlaywrightError: {pe}")
>         except Exception as e:
>             print(f"An unexpected error occurred: {e}")
>             # Optionally, log the full stack trace
>             import traceback
>             traceback.print_exc()
> 
>         # Locate and click the dark mode button
>         dark_mode_button_selector = "button[aria-checked='false'][role='switch']"
>         dark_mode_button = page.locator(dark_mode_button_selector)
> 
>         # Ensure the dark mode button is visible
>         if dark_mode_button.is_visible():
>             is_dark_mode_enabled = dark_mode_button.get_attribute("aria-checked") == "true"
>             if theme == "dark" and not is_dark_mode_enabled:
>                 dark_mode_button.click()
>             elif theme == "light" and is_dark_mode_enabled:
>                 dark_mode_button.click()
>         page.wait_for_timeout(2000)
> 
>         # Proceed with nsfw
>         nsfw_proceed_button = (
>             "#t3_12hmbug > div > div._3xX726aBn29LDbsDtzr_6E._1Ap4F5maDtT1E1YuCiaO0r"
>             ".D3IL3FD0RFy_mkKLPwL4 > div > div > button"
>         )
>         if page.locator(nsfw_proceed_button).is_visible():
>             page.locator(nsfw_proceed_button).click()
>             page.wait_for_load_state()
> 
>         # Take screenshot of the post content
>         op_path = f"./assets/temp/{reddit_thread.id}/png/title.png"
>         if my_config["settings"]["zoom"] != 1:
>             zoom = my_config["settings"]["zoom"]
>             page.evaluate(f"document.body.style.zoom={zoom}")
>             location = page.locator('[data-test-id="post-content"]').bounding_box()
>             for key in location:
>                 location[key] = float("{:.2f}".format(location[key] * zoom))
>             page.screenshot(clip=location, path=op_path)
>             location = page.locator('[data-adclicklocation="title"]').bounding_box()
>             for key in location:
>                 location[key] = float("{:.2f}".format(location[key] * zoom))
>         else:
>             page.locator('[data-test-id="post-content"]').screenshot(path=op_path)
>         print("Saved: ", op_path)
>         # print("Screenshot for OP completed")
> 
>         # Take screenshots of the comments
>         for idx, comment in enumerate(reddit_comments):
>             comments_path = f"./assets/temp/{reddit_thread.id}/png/{idx}.png"
> 
>             if page.locator('[data-testid="content-gate"]').is_visible():
>                 page.locator('[data-testid="content-gate"] button').click()
> 
>             page.goto(f'https://new.reddit.com{comment.permalink}', timeout=0)
>             if my_config["settings"]["zoom"] != 1:
>                 zoom = my_config["settings"]["zoom"]
>                 page.evaluate(f"document.body.style.zoom={zoom}")
>                 location = page.locator(f"#t1_{comment.id}").bounding_box()
>                 for key in location:
>                     location[key] = float("{:.2f}".format(location[key] * zoom))
>                 page.screenshot(clip=location, path=comments_path)
>             else:
>                 page.locator(f"#t1_{comment.id}").screenshot(path=comments_path)
>             print("Saved: ", comments_path)
>             # print(f"Screenshot for {idx + 1} comment out of {len(reddit_comments)}")
> 
>         browser.close()
> 
>     print("Screenshots downloaded successfully.")
> except Exception as e:
>     print(f"An error occurred while taking screenshots: {e}")
>     import traceback
>     traceback.print_exc()
> ```

Here is changes

Context Manager Usage for Playwright: The with sync_playwright() as p: context manager ensures that the Playwright instance is correctly started and stopped, managing resources properly. This helps avoid the "Event loop is closed" error by ensuring that all tasks within the context are completed before closing the Playwright instance.

Error Handling Inside the Context Manager: All operations related to Playwright (browser launching, page interactions, etc.) are wrapped inside the with sync_playwright() as p: block. This ensures that any exception that occurs is caught within the context where Playwright is active, preventing premature closure of the event loop.

Proper Browser Closure: The browser.close() command is placed within the context manager to ensure the browser is closed properly only after all actions are completed. This avoids issues related to resources being released too early.

Exception Handling: The error handling blocks (try/except) are used extensively to catch specific errors like PlaywrightTimeoutError and PlaywrightError, providing detailed messages and stack traces. This ensures that errors are handled gracefully and provides better debugging information.

Ensuring Cookie Handling: The code ensures that cookies are correctly loaded and managed within the browser context. This can prevent issues related to session management and unexpected behavior due to missing or incorrect cookies.

Visibility Checks and Actions: The code checks for the visibility of elements (like the dark mode button and NSFW proceed button) before interacting with them. This ensures that the interactions are only attempted when the elements are available and visible on the page.
