### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by LeakyEarth2000** [nssharmaofficial/reddit-hole#2]
`C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "c:\Users\me\Desktop\reddit-hole-main\main.py", line 17, in <module>
    from utils.videomaker import make_final_video
  File "c:\Users\me\Desktop\reddit-hole-main\utils\videomaker.py", line 19, in <module>
    from utils.captions import transcribe_audio_with_whisper, format_captions_whisper
  File "c:\Users\me\Desktop\reddit-hole-main\utils\captions.py", line 1, in <module>
    import whisper
  File "C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\ctypes\__init__.py", line 369, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable`

Shows 2 seconds after running. Unsure what to do

**Comment by nssharmaofficial** [comment]
Thanks for noting this. 

> RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

Media processing libraries like `pydub` require [`FFmpeg`](https://ffmpeg.org/download.html). After installing, add it to the system path. To verify installation try:

```bash
ffmpeg -version
```

> Traceback (most recent call last): File "c:\Users\me\Desktop\reddit-hole-main\main.py", line 17, in <module> from utils.videomaker import make_final_video File "c:\Users\me\Desktop\reddit-hole-main\utils\videomaker.py", line 19, in <module> from utils.captions import transcribe_audio_with_whisper, format_captions_whisper File "c:\Users\me\Desktop\reddit-hole-main\utils\captions.py", line 1, in <module> import whisper File

The error in the `whisper` library is probably caused by a wrongly configured environment. You can try updating `whisper`:

```bash
pip install --upgrade openai-whisper
``` 

or if that does not work, simply reinstall it:

```bash
pip uninstall openai-whisper
pip install openai-whisper
```
