### ISSUE TITLE
Background video file path error

### ISSUE THREAD

**Issue by Mregy1** [nssharmaofficial/reddit-hole#3]
Hi,
I am having hard time to find a solution for this error:
![Capturez](https://github.com/user-attachments/assets/849b3f79-be1a-4d58-9028-05bfa94762dd)

I added that to the .env file:
 # .env
BACKGROUND="/reddit-hole/assets/background/minecraft.mp4"

config.toml is untouched regarding the background part.

I double checked the file name and file path. I even added the full path and still not working. What should I do?

**Comment by nssharmaofficial** [comment]
From your terminal it seems like you have named the repository different, you have to change the background path accordingly. 

Try to paste the whole `"C:/Users/m_ess/Downloads/Compressed/reddit-hole-main/reddit-hole-main/assets/background/minecraft.mp4"` as path (or wherever you downloaded the `.mp4`)

**Comment by Mregy1** [comment]
> From your terminal it seems like you have named the repository different, you have to change the background path accordingly.
> 
> Try to paste the whole `"C:/Users/m_ess/Downloads/Compressed/reddit-hole-main/reddit-hole-main/assets/background/minecraft.mp4"` as path (or wherever you downloaded the `.mp4`)

Thanks, it worked. Finally something working apart from [RedditVideoMakerBot]!

Before running Reddit-hole, I changed resolution_width to 1080 and length to 1920 in config.toml and the video created still in the original resolution (1920 x 1080 pixels), Is there something else to change for this to render Shorts?

**Comment by nssharmaofficial** [comment]
For shorts, you do not need to change anything apart from setting `storymode=false` and changing the `subreddit` in `config.toml`. The logic is already implemented to flip the resolutions - thats why you got again the `1920x1080`.

**Comment by Mregy1** [comment]
Thank you
