### ISSUE TITLE
No thread found" Exiting ...

### ISSUE THREAD

**Issue by Mregy1** [nssharmaofficial/reddit-hole#4]
Hi
Why am I getting this message "No thread found" Exiting ..." when I used subreddit like 'AskWomen' although it has threads already?

**Comment by nssharmaofficial** [comment]
Did you get the message `Bot logged in to Reddit successfully!`?

**Comment by Mregy1** [comment]
Yes. I've just tried again.
C:\Users\m_ess\Downloads\Compressed\reddit-hole-main\reddit-hole-main>python main.py
Comments mode is on for subreddit: AskWomen
Bot logged in to Reddit successfully!
No thread found! Exiting...

**Comment by nssharmaofficial** [comment]
Okay I have just checked the subreddit `AskWomen`. The issue is that the whole subreddit is NSFW and currently there is no implementation to allow NSFW posts.

**Comment by Mregy1** [comment]
Got it!
